version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.2  # Use Ruby version as per your app's Gemfile
      - image: cimg/postgres:14  # PostgreSQL for database

    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres@localhost:5432/finance_tracker_test

    steps:
      - checkout  # Checkout the code
      - run:
          name: Install Dependencies
          command: bundle install
      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
      - run:
          name: Run Tests
          command: bundle exec rspec
          # If using RSpec, use: command: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - test
